import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { app } from "electron";
import type { AppLocale, LocalizedPromptTemplateFields, PromptTemplate } from "@shared/types";

const DEFAULT_SYSTEM_PROMPTS: Record<AppLocale, string> = {
  zh: "你是一位网站协议分析专家。你的任务是分析用户在网站上的操作过程中产生的HTTP请求、JS调用和存储变化，识别其业务场景，并生成结构化的协议分析报告。Be precise and technical. Output in Chinese (Simplified).",
  en: "You are a web protocol analysis expert. Analyze HTTP requests, JS calls, and storage changes generated by user actions, identify the business scenario, and produce a structured protocol analysis report. Be precise and technical. Output in English.",
  ru: "Ты эксперт по анализу веб-протоколов. Анализируй HTTP-запросы, JS-вызовы и изменения хранилищ, возникшие при действиях пользователя, определяй бизнес-сценарий и формируй структурированный отчёт анализа протокола. Пиши точно и технически. Отвечай на русском языке.",
};

const REQUIREMENTS: Record<AppLocale, Record<string, string>> = {
  zh: {
    auto: `1. 场景识别：判断用户执行了什么操作（注册、登录、AI对话、支付等）
2. 交互流程概述：按时间顺序描述完整交互链路
3. API端点清单：列出所有关键API，标注方法、路径、用途
4. 鉴权机制分析：认证方式、凭据获取流程、凭据传递方式
5. 流式通信分析（如检测到SSE/WebSocket）：协议类型、端点、请求/响应格式
6. 存储使用分析：Cookie/localStorage/sessionStorage 的关键变化
7. 关键依赖关系：请求之间的依赖和时序关系
8. 复现建议：用代码伪逻辑描述如何复现整个流程`,
    "reverse-api": `1. 完整 API 端点清单：列出所有 API 的方法、路径、请求参数、响应 JSON 结构
2. 鉴权流程：Token/Cookie 获取、刷新、传递机制的完整链路
3. 请求依赖链：哪些请求的响应是后续请求的必要输入
4. 数据模型推断：从 API 响应结构推断后端数据模型
5. 复现代码：用 Python requests 库写出可直接运行的完整 API 调用流程`,
    "security-audit": `1. 认证安全：分析认证方式的安全性，是否存在弱口令、明文传输、Token 泄露风险
2. 敏感数据暴露：检查响应中是否包含不必要的敏感信息（密码、密钥、PII）
3. CSRF/XSS 风险：分析请求是否缺少 CSRF Token，响应头是否缺少安全头（CSP, X-Frame-Options 等）
4. 权限控制：分析是否存在越权访问的可能（水平/垂直越权）
5. 安全建议：针对发现的问题给出具体修复建议`,
    performance: `1. 请求时序分析：分析请求的串行/并行关系，识别阻塞链路
2. 冗余请求：识别重复或不必要的请求
3. 资源优化：分析资源加载顺序，识别可优化的静态资源
4. 缓存策略：分析 Cache-Control、ETag 等缓存头的使用情况
5. 性能建议：给出具体的性能优化建议和预期收益`,
    "crypto-reverse": `1. 加密算法识别：识别所有使用的加密/签名/哈希算法（AES、RSA、SHA、HMAC、SM2/3/4 等），标注具体库和方法名
2. 加密流程还原：完整描述每个请求参数的加密 pipeline（明文 → 各步骤 → 密文），画出数据流转图
3. 密钥管理分析：密钥来源（硬编码/动态/协商）、密钥格式（Hex/Base64/PEM）、密钥长度
4. 签名/校验机制：请求签名的生成算法、参与签名的参数排序规则、时间戳/nonce 机制
5. 复现代码：用 Python 写出完整的加密/签名/请求复现代码，确保可直接运行，包含所有必要的密钥和参数`,
  },
  en: {
    auto: `1. Identify the scenario: what the user did (registration, login, AI chat, payment, etc.).
2. Summarize the interaction flow in chronological order.
3. List key API endpoints with method, path, and purpose.
4. Analyze authentication: method, credential acquisition, and credential transmission.
5. Analyze streaming communication if SSE/WebSocket is detected: protocol, endpoint, request and response format.
6. Analyze storage usage: key Cookie/localStorage/sessionStorage changes.
7. Explain request dependencies and ordering.
8. Provide reproduction guidance with pseudologic or runnable steps.`,
    "reverse-api": `1. Complete API endpoint list: methods, paths, request parameters, and response JSON structures.
2. Authentication flow: Token/Cookie acquisition, refresh, and transmission.
3. Request dependency chain.
4. Data model inference from API responses.
5. Reproduction code using Python requests.`,
    "security-audit": `1. Authentication security: weak credentials, plaintext transport, Token leakage risks.
2. Sensitive data exposure: passwords, keys, PII, and unnecessary response fields.
3. CSRF/XSS risks and missing security headers.
4. Authorization controls and privilege escalation risks.
5. Concrete remediation recommendations.`,
    performance: `1. Request timing and blocking chains.
2. Duplicate or unnecessary requests.
3. Resource loading order and optimization opportunities.
4. Cache-Control, ETag, and caching policy analysis.
5. Concrete performance recommendations and expected impact.`,
    "crypto-reverse": `1. Identify encryption/signing/hash algorithms, libraries, and methods.
2. Reconstruct the crypto flow for request parameters.
3. Analyze key management: source, format, and length.
4. Analyze signature/verification rules, parameter ordering, timestamp/nonce.
5. Provide complete Python reproduction code.`,
  },
  ru: {
    auto: `1. Определить сценарий: что сделал пользователь (регистрация, вход, AI-чат, оплата и т.п.).
2. Описать цепочку взаимодействий по времени.
3. Составить список ключевых API: метод, путь и назначение.
4. Разобрать аутентификацию: способ, получение и передачу учётных данных.
5. Разобрать потоковую коммуникацию, если есть SSE/WebSocket: протокол, endpoint, формат запроса и ответа.
6. Описать использование хранилищ: ключевые изменения Cookie/localStorage/sessionStorage.
7. Показать зависимости и порядок запросов.
8. Дать рекомендации по воспроизведению: псевдологика или кодовый план полного сценария.`,
    "reverse-api": `1. Полный список API endpoint: метод, путь, параметры запроса и JSON-структура ответа.
2. Цепочка аутентификации: получение, обновление и передача Token/Cookie.
3. Зависимости запросов: какие ответы нужны последующим запросам.
4. Вывод модели данных по структурам API-ответов.
5. Код воспроизведения: полный запускаемый сценарий на Python requests.`,
    "security-audit": `1. Безопасность аутентификации: слабые места, plaintext, риск утечки Token.
2. Утечки чувствительных данных: пароль, ключи, PII и лишние поля в ответах.
3. CSRF/XSS и заголовки безопасности: CSRF Token, CSP, X-Frame-Options и т.п.
4. Контроль доступа: риск горизонтального или вертикального повышения привилегий.
5. Практические рекомендации по исправлению найденных проблем.`,
    performance: `1. Тайминг запросов: последовательность/параллельность и блокирующие цепочки.
2. Повторные или лишние запросы.
3. Оптимизация загрузки ресурсов и порядка их получения.
4. Cache-Control, ETag и другие политики кэширования.
5. Конкретные рекомендации по ускорению и ожидаемый эффект.`,
    "crypto-reverse": `1. Определить алгоритмы шифрования, подписи и хэша (AES, RSA, SHA, HMAC, SM2/3/4 и т.п.), библиотеки и методы.
2. Восстановить поток шифрования параметров: открытый текст -> шаги -> шифртекст.
3. Разобрать управление ключами: источник, формат, длина.
4. Разобрать подпись/проверку: алгоритм, порядок параметров, timestamp/nonce.
5. Дать полный Python-код воспроизведения шифрования, подписи и запроса.`,
  },
};

interface TemplateLabel {
  name: string;
  description: string;
}

const TEMPLATE_LABELS: Record<AppLocale, Record<string, TemplateLabel>> = {
  zh: {
    auto: {
      name: "自动识别",
      description: "默认 — AI 自动检测场景并生成通用分析",
    },
    "reverse-api": {
      name: "逆向 API 协议",
      description: "聚焦 API 端点、请求/响应模式、鉴权流程、数据模型、复现代码",
    },
    "security-audit": {
      name: "安全审计",
      description: "聚焦认证安全、敏感数据暴露、CSRF/XSS 风险、权限控制",
    },
    performance: {
      name: "性能分析",
      description: "聚焦请求时序、冗余请求、资源加载、缓存策略",
    },
    "crypto-reverse": {
      name: "JS加密逆向",
      description: "聚焦JS加密算法识别、加密流程还原、密钥分析、Python复现代码",
    },
  },
  en: {
    auto: {
      name: "Auto Detect",
      description: "Default — let AI detect the scenario and produce a general analysis",
    },
    "reverse-api": {
      name: "Reverse API Protocol",
      description: "Focus on API endpoints, request/response patterns, authentication flow, data models, and reproduction code",
    },
    "security-audit": {
      name: "Security Audit",
      description: "Focus on authentication security, sensitive data exposure, CSRF/XSS risks, and authorization controls",
    },
    performance: {
      name: "Performance Analysis",
      description: "Focus on request timing, redundant requests, resource loading, and cache strategy",
    },
    "crypto-reverse": {
      name: "JS Crypto Reverse",
      description: "Focus on JS crypto algorithm detection, crypto flow reconstruction, key analysis, and Python reproduction code",
    },
  },
  ru: {
    auto: {
      name: "Автоопределение",
      description: "По умолчанию — AI сам определяет сценарий и формирует общий анализ",
    },
    "reverse-api": {
      name: "Реверс API-протокола",
      description: "Фокус на API endpoint, схемах запросов и ответов, аутентификации, модели данных и коде воспроизведения",
    },
    "security-audit": {
      name: "Аудит безопасности",
      description: "Фокус на безопасности аутентификации, утечках данных, рисках CSRF/XSS и контроле доступа",
    },
    performance: {
      name: "Анализ производительности",
      description: "Фокус на тайминге запросов, лишних запросах, загрузке ресурсов и политике кэширования",
    },
    "crypto-reverse": {
      name: "Реверс JS-шифрования",
      description: "Фокус на JS-алгоритмах шифрования, восстановлении crypto-flow, ключах и Python-коде воспроизведения",
    },
  },
};

const BUILTIN_TEMPLATE_IDS = ["auto", "reverse-api", "security-audit", "performance", "crypto-reverse"] as const;

function buildLocalizedFields(id: string, locale: AppLocale): LocalizedPromptTemplateFields {
  return {
    ...TEMPLATE_LABELS[locale][id],
    systemPrompt: DEFAULT_SYSTEM_PROMPTS[locale],
    requirements: REQUIREMENTS[locale][id],
  };
}

function getDefaultTemplates(): PromptTemplate[] {
  return BUILTIN_TEMPLATE_IDS.map((id) => ({
    id,
    ...buildLocalizedFields(id, "zh"),
    isBuiltin: true,
    isModified: false,
    localizations: {
      en: buildLocalizedFields(id, "en"),
      ru: buildLocalizedFields(id, "ru"),
    },
  }));
}

function getTemplatesPath(): string {
  return join(app.getPath("userData"), "prompt-templates.json");
}

function mergeBuiltinDefaults(templates: PromptTemplate[]): PromptTemplate[] {
  const defaults = getDefaultTemplates();
  const defaultsById = new Map(defaults.map((template) => [template.id, template]));
  const merged = templates.map((template) => {
    const defaultTemplate = defaultsById.get(template.id);
    if (!defaultTemplate || !template.isBuiltin) return template;
    return {
      ...defaultTemplate,
      ...template,
      localizations: {
        ...defaultTemplate.localizations,
        ...template.localizations,
      },
    };
  });

  const existingIds = new Set(merged.map((template) => template.id));
  for (const defaultTemplate of defaults) {
    if (!existingIds.has(defaultTemplate.id)) {
      merged.push(defaultTemplate);
    }
  }
  return merged;
}

/**
 * Load templates from disk. Initializes with defaults if file does not exist.
 */
export function loadTemplates(): PromptTemplate[] {
  const path = getTemplatesPath();
  if (!existsSync(path)) {
    const defaults = getDefaultTemplates();
    writeFileSync(path, JSON.stringify(defaults, null, 2), "utf-8");
    return defaults;
  }

  try {
    const templates = JSON.parse(readFileSync(path, "utf-8")) as PromptTemplate[];
    return mergeBuiltinDefaults(templates);
  } catch {
    const defaults = getDefaultTemplates();
    writeFileSync(path, JSON.stringify(defaults, null, 2), "utf-8");
    return defaults;
  }
}

function persistTemplates(templates: PromptTemplate[]): void {
  writeFileSync(getTemplatesPath(), JSON.stringify(templates, null, 2), "utf-8");
}

export function localizeTemplate(template: PromptTemplate, locale: AppLocale = "zh"): PromptTemplate {
  if (!template.isBuiltin || template.isModified) return template;
  if (locale === "zh") return template;
  const localized = template.localizations?.[locale];
  if (!localized) return template;
  return {
    ...template,
    ...localized,
  };
}

export function localizeTemplates(templates: PromptTemplate[], locale: AppLocale = "zh"): PromptTemplate[] {
  return templates.map((template) => localizeTemplate(template, locale));
}

/**
 * Save (create or update) a template.
 */
export function saveTemplate(template: PromptTemplate): void {
  const templates = loadTemplates();
  const idx = templates.findIndex((t) => t.id === template.id);
  if (idx >= 0) {
    // Update existing template. Built-ins stay resettable through the default map.
    if (templates[idx].isBuiltin) {
      template.isBuiltin = true;
      template.isModified = true;
    }
    templates[idx] = template;
  } else {
    template.isBuiltin = false;
    template.isModified = false;
    templates.push(template);
  }
  persistTemplates(templates);
}

/**
 * Delete a custom template. Builtin templates cannot be deleted.
 */
export function deleteTemplate(id: string): void {
  const templates = loadTemplates();
  const target = templates.find((t) => t.id === id);
  if (target?.isBuiltin) {
    throw new Error("Cannot delete builtin template");
  }
  persistTemplates(templates.filter((t) => t.id !== id));
}

/**
 * Reset a builtin template to its default values.
 */
export function resetTemplate(id: string): void {
  const templates = loadTemplates();
  const defaults = getDefaultTemplates();
  const defaultTemplate = defaults.find((t) => t.id === id);
  if (!defaultTemplate) {
    throw new Error(`No builtin default for template: ${id}`);
  }
  const idx = templates.findIndex((t) => t.id === id);
  if (idx >= 0) {
    templates[idx] = { ...defaultTemplate };
  } else {
    templates.push({ ...defaultTemplate });
  }
  persistTemplates(templates);
}

/**
 * Find a template by ID. Returns undefined if not found.
 */
export function findTemplate(id: string, locale: AppLocale = "zh"): PromptTemplate | undefined {
  const template = loadTemplates().find((t) => t.id === id);
  return template ? localizeTemplate(template, locale) : undefined;
}
